In [1]:
import pandas as pd
import os
import xlsxwriter

base_geral = pd.read_excel('C:/Users/mathe/Codes/Italiano_campeonato/ITALIANO_2020.xlsx')
confrontos = base_geral[['Confronto','Data']]
confrontos = confrontos.drop_duplicates()


writer = pd.ExcelWriter('C:/Users/mathe/Codes/Italiano_campeonato/Confrontos.xlsx')
confrontos.to_excel(writer,"Confrontos")
writer.save()

In [2]:
import pandas as pd

base = pd.read_excel("fifa_20.xlsx")

base

,v_fifa,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,fifa_20,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andr√©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,fifa_20,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,fifa_20,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,fifa_20,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,fifa_20,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53635,fifa_18,237463,https://sofifa.com/player/237463/adam-kelsey/1...,A. Kelsey,Adam Kelsey,17,1999-11-12,188,74,England,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53636,fifa_18,231381,https://sofifa.com/player/231381/jordan-young/...,J. Young,Jordan Young,17,1999-07-31,175,71,Scotland,...,32+1,30+1,30+1,30+1,32+1,32+1,29+1,29+1,29+1,32+1
53637,fifa_18,240404,https://sofifa.com/player/240404/jack-keeble/1...,J. Keeble,Jack Keeble,18,1999-03-22,172,66,England,...,44+1,41+1,41+1,41+1,44+1,46+1,45+1,45+1,45+1,46+1
53638,fifa_18,11728,https://sofifa.com/player/11728/barry-richards...,B. Richardson,Barry Richardson,47,1969-08-05,185,77,England,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53639,fifa_18,235352,https://sofifa.com/player/235352/tommy-kassemo...,T. K√§√üemodel,Tommy K√§√üemodel,28,1988-08-09,173,75,Germany,...,39+1,43+1,43+1,43+1,39+1,38+1,39+1,39+1,39+1,38+1

## Dicion√°rio

In [3]:
df = pd.DataFrame({'col1': {0: 'w', 1: "Inter", 2: "Internazionale"}})
di = {"Atalanta":"Atalanta",
      "Bologna":"Bologna",
      "Brescia":"Brescia",
      "Cagliari":"Cagliari",
      "Fiorentina":"Fiorentina",
      "Genoa":"Genoa",
      "Hellas Verona":"Hellas Verona",
      "Internazionale":"Inter",
      "Juventus":"Juventus",
      "Lazio":"Lazio",
      "Lecce":"Lecce",
      "Milan":"Milan",
      "Napoli":"Napoli",
      "Parma":"Parma",
      "Roma":"Roma",
      "Sampdoria":"Sampdoria",
      "Sassuolo":"Sassuolo",
      "SPAL":"SPAL",
      "Torino":"Torino",
      "Udinese":"Udinese",
     }


df.replace({"col1": di})

    col1
0      w
1  Inter
2  Inter

## Base com as m√©dias FIFA

In [4]:
base_gk = base[base.player_positions.eq("GK")]
base_gk_2020 = base[base.v_fifa.eq("fifa_20")]
base_players = base[base.player_positions != ("GK")]
base_players_2020 = base[base.v_fifa.eq("fifa_20")]

base_consulta_gk_2020 = base_gk.groupby('club').mean()
base_consulta_players_2020 = base_players.groupby('club').mean()

In [5]:
base_consulta_players_2020 = base_consulta_players_2020.dropna(axis="columns")
base_consulta_players_2020 = base_consulta_players_2020.drop(["wage_eur","value_eur"],axis=1)
base_consulta_players_2020

,sofifa_id,age,height_cm,weight_kg,overall,potential,international_reputation,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic
club,,,,,,,,,,,,,,,
SSV Jahn Regensburg,221176.680556,25.263889,183.222222,77.111111,64.944444,69.361111,1.000000,3.138889,2.416667,66.041667,49.486111,52.847222,59.472222,48.805556,65.347222
1. FC Heidenheim 1846,218209.150685,24.397260,183.369863,78.890411,66.273973,71.753425,1.000000,3.027397,2.465753,67.287671,52.438356,55.205479,61.109589,49.643836,64.712329
1. FC Kaiserslautern,222807.684932,23.561644,183.301370,77.863014,64.602740,70.698630,1.000000,3.150685,2.369863,68.232877,50.232877,53.657534,59.232877,45.534247,64.780822
1. FC K√∂ln,210236.946667,24.426667,182.840000,77.253333,72.333333,77.666667,1.360000,3.146667,2.653333,69.573333,56.213333,63.200000,67.933333,58.346667,68.040000
1. FC Magdeburg,228037.283582,24.641791,183.970149,77.223881,65.119403,69.671642,1.014925,3.298507,2.402985,67.746269,49.835821,53.701493,59.358209,49.343284,66.880597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zenit St. Petersburg,202649.807692,25.961538,182.038462,75.153846,73.769231,77.615385,1.423077,3.076923,2.576923,72.538462,58.923077,66.153846,67.884615,59.500000,67.692308
√áaykur Rizespor,214795.638298,25.510638,180.872340,75.489362,67.425532,72.319149,1.000000,2.893617,2.574468,66.553191,54.063830,58.978723,64.446809,54.042553,64.234043
√ñrebro SK,218734.826087,25.043478,181.260870,75.710145,61.173913,65.927536,1.000000,2.666667,2.246377,66.420290,45.608696,50.956522,56.971014,45.231884,62.739130
√ñstersunds FK,223749.265625,23.531250,180.468750,75.031250,62.718750,68.781250,1.000000,2.812500,2.296875,68.781250,47.953125,55.140625,61.093750,47.218750,64.843750
≈ölƒÖsk Wroc≈Çaw,226516.500000,23.000000,178.000000,65.000000,62.500000,67.500000,1.000000,3.000000,2.500000,76.500000,46.000000,53.000000,64.000000,38.500000,49.000000

In [6]:
base_consulta_gk_2020 =base_consulta_gk_2020[["gk_diving","gk_handling","gk_kicking","gk_reflexes","gk_speed","gk_positioning"]]
base_consulta_gk_2020

,gk_diving,gk_handling,gk_kicking,gk_reflexes,gk_speed,gk_positioning
club,,,,,,
SSV Jahn Regensburg,64.000000,60.500000,61.200000,64.400000,33.800000,57.400000
1. FC Heidenheim 1846,65.200000,61.700000,56.900000,66.300000,39.400000,61.900000
1. FC Kaiserslautern,61.000000,58.000000,55.333333,61.222222,36.222222,59.333333
1. FC K√∂ln,68.916667,65.000000,64.666667,68.750000,37.916667,64.916667
1. FC Magdeburg,66.000000,61.000000,55.500000,65.500000,38.000000,61.000000
...,...,...,...,...,...,...
Zag≈Çƒôbie Sosnowiec,61.666667,58.666667,62.333333,61.666667,36.666667,56.000000
Zenit St. Petersburg,74.000000,70.500000,69.000000,77.250000,45.250000,71.500000
√áaykur Rizespor,65.333333,64.166667,60.666667,70.500000,42.000000,65.000000
√ñrebro SK,61.125000,57.125000,55.375000,60.750000,35.125000,58.250000
√ñstersunds FK,63.111111,57.444444,61.444444,61.777778,31.666667,55.555556

## Base Estatisticas Medias

In [7]:
base_ita = pd.read_excel("ITALIANO_2020.xlsx")

base_ita = base_ita.drop(["Unnamed: 0","Unnamed: 0.1"],axis=1)

base_ita

,Player,#,Nation,Pos,Min,Gls,Ast,PK,PKatt,Sh,...,Carries,PrgDist.1,Succ,Att.1,Time,Time_Adversario,Confronto,Data,Estadio,Torcida
0,Luis Muriel,9,co COL,FW,77.0,0,0,0,0,5,...,25.0,84.0,1.0,1.0,Atalanta,Cagliari,Atalanta_vs_Cagliari,2019-11-03,"Stadio Atleti Azzurri d'Italia, Bergamo","18,617"
1,Musa Barrow,99,gm GAM,FW,13.0,0,0,0,0,2,...,9.0,27.0,1.0,1.0,Atalanta,Cagliari,Atalanta_vs_Cagliari,2019-11-03,"Stadio Atleti Azzurri d'Italia, Bergamo","18,617"
2,Josip Iliƒçiƒá,72,si SVN,FW,38.0,0,0,0,0,1,...,21.0,27.0,0.0,0.0,Atalanta,Cagliari,Atalanta_vs_Cagliari,2019-11-03,"Stadio Atleti Azzurri d'Italia, Bergamo","18,617"
3,Papu G√≥mez,10,ar ARG,AM,45.0,0,0,0,0,1,...,20.0,59.0,0.0,1.0,Atalanta,Cagliari,Atalanta_vs_Cagliari,2019-11-03,"Stadio Atleti Azzurri d'Italia, Bergamo","18,617"
4,Ruslan Malinovskyi,18,ua UKR,AM,45.0,0,0,0,0,4,...,45.0,126.0,5.0,6.0,Atalanta,Cagliari,Atalanta_vs_Cagliari,2019-11-03,"Stadio Atleti Azzurri d'Italia, Bergamo","18,617"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7133,Cristian Ansaldi,15,ar ARG,WB,90.0,0,0,0,0,1,...,51.0,282.0,4.0,5.0,Torino,Udinese,Udinese_vs_Torino,2019-10-20,"Dacia Arena, Udine","24,049"
7134,Lyanco,4,br BRA,CB,90.0,0,0,0,0,0,...,51.0,126.0,1.0,2.0,Torino,Udinese,Udinese_vs_Torino,2019-10-20,"Dacia Arena, Udine","24,049"
7135,Nicolas Nkoulou,33,cm CMR,CB,90.0,0,0,0,0,0,...,41.0,48.0,0.0,0.0,Torino,Udinese,Udinese_vs_Torino,2019-10-20,"Dacia Arena, Udine","24,049"
7136,Armando Izzo,5,it ITA,CB,90.0,0,0,0,0,0,...,47.0,132.0,1.0,2.0,Torino,Udinese,Udinese_vs_Torino,2019-10-20,"Dacia Arena, Udine","24,049"
7137,Salvatore Sirigu,39,it ITA,GK,90.0,0,0,0,0,0,...,4.0,2.0,0.0,0.0,Torino,Udinese,Udinese_vs_Torino,2019-10-20,"Dacia Arena, Udine","24,049"

In [8]:
base_ita_new = base_ita.groupby(['Confronto','Time',"Data"], as_index=False)['Gls','Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR',
       'Touches', 'Press', 'Tkl', 'Int', 'Blocks',].sum()



import numpy as np

new_data_1 = []
for i in base_ita_new.Data:
    i = str(i).replace("-","")
    new_data_1.append(i)

base_ita_new["Data_new"] = pd.DataFrame(np.array(new_data_1))




media_sh = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["Sh"].mean()
    media_sh.append(oi)
    
base_ita_new["media_Sh"] = pd.DataFrame(np.array(media_sh))

######

media_sot = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["SoT"].mean()
    media_sot.append(oi)
    
base_ita_new["media_SoT"] = pd.DataFrame(np.array(media_sot))

######

media_crdy = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["CrdY"].mean()
    media_crdy.append(oi)
    
base_ita_new["media_CrdY"] = pd.DataFrame(np.array(media_crdy))

######

media_touches = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["Touches"].mean()
    media_touches.append(oi)
    
base_ita_new["media_Touches"] = pd.DataFrame(np.array(media_touches))

######

media_tkl = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["Tkl"].mean()
    media_tkl.append(oi)
    
base_ita_new["media_Tkl"] = pd.DataFrame(np.array(media_tkl))

######

media_int = []

for i, j in zip(base_ita_new["Data_new"],base_ita_new["Time"]):
    oi = base_ita_new.loc[base_ita_new["Data_new"]<i]
    oi = oi.loc[oi["Time"]==j]
    oi = oi["Int"].mean()
    media_int.append(oi)
    
base_ita_new["media_Int"] = pd.DataFrame(np.array(media_int))

time_fora = []

for i in base_ita_new.Confronto:
    i = str(i)
    i = i.split("_vs_")
    i_1 = str(i[1])
    i_2 = str(i[1])
    a = "Hellas"
    if a in i_1:
        i_1 = i_1.replace("_"," ")
        time_fora.append(i_1)
    else:
        time_fora.append(i_2)
        
        
base_ita_new["Time_Fora"] = pd.DataFrame(np.array(time_fora))


time_casa = []

for i in confrontos.Confronto:
    i = str(i)
    i = i.split("_vs_")
    i_1 = str(i[0])
    i_2 = str(i[0])
    a = "Hellas"
    if a in i_1:
        i_1 = i_1.replace("_"," ")
        time_casa.append(i_1)
    else:
        time_casa.append(i_2)
        
        
base_ita_new["Time_Casa"] = pd.DataFrame(np.array(time_casa))


base_ita_new

C:\Users\mathe\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

,Confronto,Time,Data,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,...,Blocks,Data_new,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,Time_Fora,Time_Casa
0,Atalanta_vs_Cagliari,Atalanta,2019-11-03,0,0,0,0,19,2,2,...,15.0,20191103,20.700000,8.000000,2.000000,659.200000,20.100000,10.200000,Cagliari,Atalanta
1,Atalanta_vs_Cagliari,Cagliari,2019-11-03,1,1,0,0,13,3,3,...,27.0,20191103,11.000000,3.200000,2.900000,514.600000,16.700000,9.100000,Cagliari,Atalanta
2,Atalanta_vs_Fiorentina,Atalanta,2019-09-22,2,1,0,0,19,3,2,...,9.0,20190922,22.333333,8.666667,2.000000,577.333333,18.000000,6.666667,Fiorentina,Atalanta
3,Atalanta_vs_Fiorentina,Fiorentina,2019-09-22,2,1,0,0,9,2,5,...,24.0,20190922,18.333333,5.000000,1.666667,554.333333,14.333333,8.333333,Fiorentina,Atalanta
4,Atalanta_vs_Genoa,Atalanta,2020-02-02,2,2,0,0,25,9,2,...,11.0,20200202,20.095238,7.380952,2.285714,681.238095,18.571429,10.380952,Genoa,Atalanta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,Udinese_vs_SPAL,Udinese,2019-11-10,0,0,0,0,17,1,3,...,17.0,20191110,13.090909,4.545455,2.636364,518.181818,16.909091,9.181818,SPAL,NaN
508,Udinese_vs_Sassuolo,Sassuolo,2020-01-12,0,0,0,0,17,3,0,...,13.0,20200112,13.888889,4.611111,2.888889,684.666667,18.388889,9.833333,Sassuolo,NaN
509,Udinese_vs_Sassuolo,Udinese,2020-01-12,3,3,0,0,14,8,0,...,27.0,20200112,12.166667,3.611111,2.444444,538.500000,16.777778,9.833333,Sassuolo,NaN
510,Udinese_vs_Torino,Torino,2019-10-20,0,0,0,0,11,3,3,...,21.0,20191020,10.142857,3.571429,2.285714,543.571429,22.142857,14.285714,Torino,NaN
511,Udinese_vs_Torino,Udinese,2019-10-20,1,1,0,0,18,4,3,...,24.0,20191020,12.428571,4.714286,2.428571,533.571429,17.285714,10.000000,Torino,NaN

## Base Confrontos Tratadas

In [9]:
confrontos = pd.read_excel("Confrontos.xlsx")
confrontos = confrontos.drop(["Unnamed: 0"],axis =1)


new_data = []
for i in confrontos.Data:
    i = str(i).replace("-","")
    new_data.append(i)

confrontos["Data_new"] = pd.DataFrame(np.array(new_data))


time_casa = []

for i in confrontos.Confronto:
    i = str(i)
    i = i.split("_vs_")
    i_1 = str(i[0])
    i_2 = str(i[0])
    a = "Hellas"
    if a in i_1:
        i_1 = i_1.replace("_"," ")
        time_casa.append(i_1)
    else:
        time_casa.append(i_2)
        
        
confrontos["Time"] = pd.DataFrame(np.array(time_casa))



time_fora = []

for i in confrontos.Confronto:
    i = str(i)
    i = i.split("_vs_")
    i_1 = str(i[1])
    i_2 = str(i[1])
    a = "Hellas"
    if a in i_1:
        i_1 = i_1.replace("_"," ")
        time_fora.append(i_1)
    else:
        time_fora.append(i_2)
        
        
confrontos["Time_Fora"] = pd.DataFrame(np.array(time_fora))
confrontos


# for i,a in zip(confrontos["Confronto"],confrontos["Data"]):
#     print(a)

                     Confronto        Data  Data_new      Time      Time_Fora
0         Atalanta_vs_Cagliari  2019-11-03  20191103  Atalanta       Cagliari
1       Atalanta_vs_Fiorentina  2019-09-22  20190922  Atalanta     Fiorentina
2            Atalanta_vs_Genoa  2020-02-02  20200202  Atalanta          Genoa
3    Atalanta_vs_Hellas_Verona  2019-12-07  20191207  Atalanta  Hellas Verona
4         Atalanta_vs_Juventus  2019-11-23  20191123  Atalanta       Juventus
..                         ...         ...       ...       ...            ...
251           Udinese_vs_Parma  2019-09-01  20190901   Udinese          Parma
252            Udinese_vs_Roma  2019-10-30  20191030   Udinese           Roma
253        Udinese_vs_Sassuolo  2020-01-12  20200112   Udinese       Sassuolo
254            Udinese_vs_SPAL  2019-11-10  20191110   Udinese           SPAL
255          Udinese_vs_Torino  2019-10-20  20191020   Udinese         Torino

[256 rows x 5 columns]

## Base Estatistica Diferenca Medias

In [10]:
base_dentro = confrontos.merge(base_ita_new, how='inner', left_on=['Confronto', "Data_new","Time"], right_on=['Confronto','Data_new',"Time"])


base_dentro = base_dentro[['Confronto', 'Data_new', 'Time','media_Sh', 'media_SoT', 'media_CrdY',
               'media_Touches', 'media_Tkl', 'media_Int','Gls']]

base_fora = base_ita_new.loc[base_ita_new["Time"] == base_ita_new["Time_Fora"]]
base_fora = base_fora[['Confronto', 'Data_new', 'Time_Fora','media_Sh', 'media_SoT', 'media_CrdY',
               'media_Touches', 'media_Tkl', 'media_Int','Gls']]

base_fora = base_fora.reset_index(drop=True)
base_fora = confrontos.merge(base_fora, how='inner', left_on=['Confronto', "Data_new","Time_Fora"], right_on=['Confronto','Data_new',"Time_Fora"])
base_fora = base_fora[['Confronto', 'Data_new', 'Time_Fora','media_Sh', 'media_SoT', 'media_CrdY','media_Touches', 'media_Tkl', 'media_Int','Gls']]
# base_dentro = base_ita_new.loc[base_ita_new["Time"] == base_ita_new["Time_Casa"]]
base_fora


base_dentro

,Confronto,Data_new,Time,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,Gls
0,Atalanta_vs_Cagliari,20191103,Atalanta,20.700000,8.000000,2.000000,659.200000,20.100000,10.200000,0
1,Atalanta_vs_Fiorentina,20190922,Atalanta,22.333333,8.666667,2.000000,577.333333,18.000000,6.666667,2
2,Atalanta_vs_Genoa,20200202,Atalanta,20.095238,7.380952,2.285714,681.238095,18.571429,10.380952,2
3,Atalanta_vs_Hellas_Verona,20191207,Atalanta,20.071429,7.214286,2.428571,673.285714,19.214286,9.857143,3
4,Atalanta_vs_Juventus,20191123,Atalanta,19.666667,7.083333,2.166667,674.416667,19.166667,10.000000,1
...,...,...,...,...,...,...,...,...,...,...
251,Udinese_vs_Parma,20190901,Udinese,19.000000,6.000000,1.000000,507.000000,14.000000,11.000000,1
252,Udinese_vs_Roma,20191030,Udinese,12.555556,4.555556,2.555556,509.444444,17.444444,9.888889,0
253,Udinese_vs_Sassuolo,20200112,Udinese,12.166667,3.611111,2.444444,538.500000,16.777778,9.833333,3
254,Udinese_vs_SPAL,20191110,Udinese,13.090909,4.545455,2.636364,518.181818,16.909091,9.181818,0
255,Udinese_vs_Torino,20191020,Udinese,12.428571,4.714286,2.428571,533.571429,17.285714,10.000000,1

## Unindo as bases (FIFA+Estat√≠sticas)

In [11]:
di = {"Atalanta":"Atalanta",
      "Bologna":"Bologna",
      "Brescia":"Brescia",
      "Cagliari":"Cagliari",
      "Fiorentina":"Fiorentina",
      "Genoa":"Genoa",
      "Hellas Verona":"Hellas Verona",
      "Internazionale":"Inter",
      "Juventus":"Juventus",
      "Lazio":"Lazio",
      "Lecce":"Lecce",
      "Milan":"Milan",
      "Napoli":"Napoli",
      "Parma":"Parma",
      "Roma":"Roma",
      "Sampdoria":"Sampdoria",
      "Sassuolo":"Sassuolo",
      "SPAL":"SPAL",
      "Torino":"Torino",
      "Udinese":"Udinese",
     }


base_fora_tratada = base_fora.replace({"Time_Fora": di})
base_fora_tratada["Time_Fora"].value_counts()


base_fora_tratada_final = base_fora_tratada.merge(base_consulta_players_2020, how='inner', left_on=["Time_Fora"], right_on=["club"])

In [12]:
base_dentro_tratada = base_dentro.replace({"Time": di})
base_dentro_tratada["Time"].value_counts()


base_dentro_tratada_final = base_dentro_tratada.merge(base_consulta_players_2020, how='inner', left_on=["Time"], right_on=["club"])

base_fora_tratada_final = base_fora_tratada_final.sort_values(["Data_new",'Confronto'])
base_dentro_tratada_final = base_dentro_tratada_final.sort_values(["Data_new",'Confronto'])


base_fora_tratada_final = base_fora_tratada_final.reset_index(drop=True)
base_dentro_tratada_final = base_dentro_tratada_final.reset_index(drop=True)

# df2 = df.sort_values(['Country Name', 'Ano'])


# base_dentro

In [13]:
bftf_0 = base_fora_tratada_final[['Confronto', 'Data_new', 'Time_Fora']]



bftf_1 = base_fora_tratada_final[['media_Sh', 'media_SoT','media_CrdY', 'media_Touches',
                                  'media_Tkl', 'media_Int','age', 'height_cm', 'weight_kg',
                                  'overall', 'potential','international_reputation', 'weak_foot',
                                  'skill_moves', 'pace','shooting', 'passing', 'dribbling', 'defending', 'physic','Gls']]


bdtf_0 = base_dentro_tratada_final[['Confronto', 'Data_new', 'Time']]



bdtf_1 = base_dentro_tratada_final[['media_Sh', 'media_SoT','media_CrdY', 'media_Touches',
                                  'media_Tkl', 'media_Int','age', 'height_cm', 'weight_kg',
                                  'overall', 'potential','international_reputation', 'weak_foot',
                                  'skill_moves', 'pace','shooting', 'passing', 'dribbling', 'defending', 'physic','Gls']]


base_final_atributos = bdtf_1 - bftf_1

In [14]:
base_final_atributos

,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,age,height_cm,weight_kg,overall,...,international_reputation,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic,Gls
0,NaN,NaN,NaN,NaN,NaN,NaN,-1.859531,3.616287,2.577169,-6.093883,...,-0.725818,-0.020270,-0.170341,-6.951636,-4.363442,-6.873755,-6.847440,-4.598506,0.208748,-1
1,NaN,NaN,NaN,NaN,NaN,NaN,1.018787,-2.588003,-4.586684,-12.699736,...,-1.292683,-0.248517,-0.422544,-4.803560,-7.125247,-11.270600,-11.049440,-12.537574,-8.200725,-1
2,NaN,NaN,NaN,NaN,NaN,NaN,2.987360,-0.633442,0.656555,5.836042,...,0.319971,0.067895,0.268328,-1.031600,8.702059,7.130553,6.661250,5.852474,1.587216,-1
3,NaN,NaN,NaN,NaN,NaN,NaN,0.190371,-2.031992,-1.990339,-3.318499,...,-0.164555,0.075546,-0.207634,-1.083307,-0.978302,-2.242319,-2.901806,-3.747070,-3.130345,0
4,NaN,NaN,NaN,NaN,NaN,NaN,-0.880415,0.492040,0.636246,4.417068,...,0.616068,0.122362,0.043317,2.865050,3.961681,3.694558,3.266198,5.054795,3.114587,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,3.840000,0.200000,-0.280000,48.040000,1.000000,1.360000,-1.371464,-0.783846,-0.047678,4.850027,...,0.602028,0.119730,0.192492,3.260452,1.579968,4.033624,4.347981,7.924924,3.791140,-1
252,-1.573333,0.635000,-0.790000,-39.311667,3.135000,0.405000,1.627276,-2.258159,-2.404157,-2.120749,...,-0.032120,0.076950,0.123325,5.640673,2.736001,-1.016317,0.503092,-2.670045,0.034524,-1
253,3.083333,0.166667,0.458333,-37.333333,3.708333,-0.083333,-0.678549,0.630394,1.356473,2.489994,...,0.263290,-0.023765,0.184490,1.881176,2.018762,3.575985,2.691682,3.118199,1.100375,2
254,-1.280000,-0.520000,-0.560000,-11.760000,-1.040000,0.400000,0.209133,1.143808,2.249381,-0.550155,...,-0.143498,-0.273529,-0.084985,-1.004644,0.058514,-0.181889,-0.661146,-1.921207,0.335449,0
255,3.443333,1.108333,0.108333,180.541667,0.948333,0.133333,0.909027,-0.402880,1.591149,6.113102,...,0.253600,0.176326,0.249034,-1.460309,6.348788,6.810854,7.230418,5.549175,0.944152,3

In [15]:
base_fora_tratada_final

,Confronto,Data_new,Time_Fora,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,Gls,...,potential,international_reputation,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic
0,Fiorentina_vs_Napoli,20190824,Napoli,NaN,NaN,NaN,NaN,NaN,NaN,4,...,81.932432,2.081081,3.270270,2.972973,74.662162,60.810811,67.702703,74.202703,61.743243,67.067568
1,Parma_vs_Juventus,20190824,Juventus,NaN,NaN,NaN,NaN,NaN,NaN,1,...,84.459459,2.500000,3.297297,3.081081,74.486486,63.283784,70.648649,76.256757,65.135135,73.432432
2,Cagliari_vs_Brescia,20190825,Brescia,NaN,NaN,NaN,NaN,NaN,NaN,1,...,72.500000,1.102564,2.974359,2.435897,68.679487,49.692308,55.038462,60.564103,52.217949,65.384615
3,Hellas_Verona_vs_Bologna,20190825,Bologna,NaN,NaN,NaN,NaN,NaN,NaN,1,...,77.844156,1.298701,2.961039,2.805195,68.766234,54.844156,61.974026,68.389610,57.051948,68.337662
4,Roma_vs_Genoa,20190825,Genoa,NaN,NaN,NaN,NaN,NaN,NaN,3,...,76.520548,1.410959,2.945205,2.794521,67.986301,56.835616,62.602740,68.301370,55.945205,65.520548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,Milan_vs_Genoa,20200308,Genoa,11.680000,3.92,3.280000,593.000000,16.760000,9.800000,2,...,76.520548,1.410959,2.945205,2.794521,67.986301,56.835616,62.602740,68.301370,55.945205,65.520548
252,Parma_vs_SPAL,20200308,SPAL,13.240000,3.24,3.040000,553.520000,15.240000,9.720000,1,...,74.802817,1.239437,2.971831,2.535211,64.042254,53.422535,60.394366,64.704225,55.267606,65.197183
253,Sampdoria_vs_Hellas_Verona,20200308,Hellas Verona,11.541667,3.75,2.583333,561.666667,15.916667,9.958333,0,...,73.804878,1.134146,3.036585,2.597561,67.682927,53.865854,59.731707,65.487805,53.304878,65.207317
254,Udinese_vs_Fiorentina,20200308,Fiorentina,14.520000,4.44,2.800000,559.400000,18.200000,9.120000,0,...,79.013158,1.355263,3.250000,2.802632,67.710526,56.447368,60.828947,67.355263,57.144737,67.276316
255,Sassuolo_vs_Brescia,20200309,Brescia,10.640000,3.60,2.600000,500.000000,16.760000,9.200000,0,...,72.500000,1.102564,2.974359,2.435897,68.679487,49.692308,55.038462,60.564103,52.217949,65.384615

In [16]:
base_dentro_tratada_final

,Confronto,Data_new,Time,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,Gls,...,potential,international_reputation,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic
0,Fiorentina_vs_Napoli,20190824,Fiorentina,NaN,NaN,NaN,NaN,NaN,NaN,3,...,79.013158,1.355263,3.250000,2.802632,67.710526,56.447368,60.828947,67.355263,57.144737,67.276316
1,Parma_vs_Juventus,20190824,Parma,NaN,NaN,NaN,NaN,NaN,NaN,0,...,71.585366,1.207317,3.048780,2.658537,69.682927,56.158537,59.378049,65.207317,52.597561,65.231707
2,Cagliari_vs_Brescia,20190825,Cagliari,NaN,NaN,NaN,NaN,NaN,NaN,0,...,75.408451,1.422535,3.042254,2.704225,67.647887,58.394366,62.169014,67.225352,58.070423,66.971831
3,Hellas_Verona_vs_Bologna,20190825,Hellas Verona,NaN,NaN,NaN,NaN,NaN,NaN,1,...,73.804878,1.134146,3.036585,2.597561,67.682927,53.865854,59.731707,65.487805,53.304878,65.207317
4,Roma_vs_Genoa,20190825,Roma,NaN,NaN,NaN,NaN,NaN,NaN,3,...,81.486486,2.027027,3.067568,2.837838,70.851351,60.797297,66.297297,71.567568,61.000000,68.635135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,Milan_vs_Genoa,20200308,Milan,15.520000,4.120000,3.000000,641.040000,17.760000,11.160000,1,...,81.896104,2.012987,3.064935,2.987013,71.246753,58.415584,66.636364,72.649351,63.870130,69.311688
252,Parma_vs_SPAL,20200308,Parma,11.666667,3.875000,2.250000,514.208333,18.375000,10.125000,0,...,71.585366,1.207317,3.048780,2.658537,69.682927,56.158537,59.378049,65.207317,52.597561,65.231707
253,Sampdoria_vs_Hellas_Verona,20200308,Sampdoria,14.625000,3.916667,3.041667,524.333333,19.625000,9.875000,2,...,77.128205,1.397436,3.012821,2.782051,69.564103,55.884615,63.307692,68.179487,56.423077,66.307692
254,Udinese_vs_Fiorentina,20200308,Udinese,13.240000,3.920000,2.240000,547.640000,17.160000,9.520000,0,...,77.917647,1.211765,2.976471,2.717647,66.705882,56.505882,60.647059,66.694118,55.223529,67.611765
255,Sassuolo_vs_Brescia,20200309,Sassuolo,14.083333,4.708333,2.708333,680.541667,17.708333,9.333333,3,...,77.534247,1.356164,3.150685,2.684932,67.219178,56.041096,61.849315,67.794521,57.767123,66.328767

In [107]:
resultado = pd.concat([bdtf_0,bftf_0.Time_Fora ,base_final_atributos], axis=1, sort=False)

gols_finais = bdtf_1.Gls + bftf_1.Gls

placar = []

for i in resultado.Gls:
    if i ==0:
        a = 3
        placar.append(a)
    elif i >0:
        a = 1
        placar.append(a)
    elif i <0:
        a = 2
        placar.append(a)

resultado["Result"] = pd.DataFrame(np.array(placar))
resultado["N_Gols"] = pd.DataFrame(np.array(gols_finais))

resultado = resultado.fillna(0)

resultado = resultado.drop(columns=['Gls'])

resultado

,Confronto,Data_new,Time,Time_Fora,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,...,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic,Result,N_Gols
0,Fiorentina_vs_Napoli,20190824,Fiorentina,Napoli,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.020270,-0.170341,-6.951636,-4.363442,-6.873755,-6.847440,-4.598506,0.208748,2,7
1,Parma_vs_Juventus,20190824,Parma,Juventus,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.248517,-0.422544,-4.803560,-7.125247,-11.270600,-11.049440,-12.537574,-8.200725,2,1
2,Cagliari_vs_Brescia,20190825,Cagliari,Brescia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.067895,0.268328,-1.031600,8.702059,7.130553,6.661250,5.852474,1.587216,2,1
3,Hellas_Verona_vs_Bologna,20190825,Hellas Verona,Bologna,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.075546,-0.207634,-1.083307,-0.978302,-2.242319,-2.901806,-3.747070,-3.130345,3,2
4,Roma_vs_Genoa,20190825,Roma,Genoa,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.122362,0.043317,2.865050,3.961681,3.694558,3.266198,5.054795,3.114587,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,Milan_vs_Genoa,20200308,Milan,Genoa,3.840000,0.200000,-0.280000,48.040000,1.000000,1.360000,...,0.119730,0.192492,3.260452,1.579968,4.033624,4.347981,7.924924,3.791140,2,3
252,Parma_vs_SPAL,20200308,Parma,SPAL,-1.573333,0.635000,-0.790000,-39.311667,3.135000,0.405000,...,0.076950,0.123325,5.640673,2.736001,-1.016317,0.503092,-2.670045,0.034524,2,1
253,Sampdoria_vs_Hellas_Verona,20200308,Sampdoria,Hellas Verona,3.083333,0.166667,0.458333,-37.333333,3.708333,-0.083333,...,-0.023765,0.184490,1.881176,2.018762,3.575985,2.691682,3.118199,1.100375,1,2
254,Udinese_vs_Fiorentina,20200308,Udinese,Fiorentina,-1.280000,-0.520000,-0.560000,-11.760000,-1.040000,0.400000,...,-0.273529,-0.084985,-1.004644,0.058514,-0.181889,-0.661146,-1.921207,0.335449,3,0
255,Sassuolo_vs_Brescia,20200309,Sassuolo,Brescia,3.443333,1.108333,0.108333,180.541667,0.948333,0.133333,...,0.176326,0.249034,-1.460309,6.348788,6.810854,7.230418,5.549175,0.944152,1,3

In [108]:
#escrevendo em excelfile
writer = pd.ExcelWriter('Base_Treino_Italiano_2020.xlsx')
resultado.to_excel(writer,"Geral")
writer.save()

Index(['Confronto', 'Data_new', 'Time', 'Time_Fora', 'media_Sh', 'media_SoT',
       'media_CrdY', 'media_Touches', 'media_Tkl', 'media_Int', 'age',
       'height_cm', 'weight_kg', 'overall', 'potential',
       'international_reputation', 'weak_foot', 'skill_moves', 'pace',
       'shooting', 'passing', 'dribbling', 'defending', 'physic', 'Gls',
       'Result', 'N_Gols'],
      dtype='object')

# Pr√≥ximos jogos

In [122]:
#Importo as bibliotecas
import pandas as pd
import requests
from bs4 import BeautifulSoup
import xlsxwriter
import os
import time

link = "2020-06-24"
req = requests.get("https://fbref.com/en/matches/"+link)
if req.status_code == 200:
    content = req.content
#pegando a base do site
soup = BeautifulSoup(content, 'html.parser')
table_geral = soup.find_all(id="sched_3260")

table_str_1 = str(table_geral)
df_1 = pd.read_html(table_str_1)[0]
resultado = df_1[["Home","Away"]]

resultado

       Home       Away
0     Inter   Sassuolo
1  Atalanta      Lazio
2      Roma  Sampdoria

In [123]:
base_consulta = base_fora_tratada_final.rename(columns={"Time_Fora":"Time"})
base_consulta_final= base_consulta.append(base_dentro_tratada_final)

In [124]:
resultado = resultado.replace({"Home": di})
resultado = resultado.replace({"Away": di})

base_nova_casa = pd.DataFrame()

for i in resultado.Home:
    a = i
    procv = base_consulta_final[base_consulta_final.Time.eq(a)]
    sort_procv = procv.sort_values(["Data_new"])
    last_game = sort_procv[len(sort_procv)-1:len(sort_procv)]
    last_game = last_game.reset_index(drop=True)
    last_game = last_game.drop(["Confronto","Data_new",'Gls','sofifa_id'],axis=1)
    base_nova_casa = base_nova_casa.append(last_game)
    
    
base_nova_fora = pd.DataFrame()

for i in resultado.Away:
    a = i
    procv = base_consulta_final[base_consulta_final.Time.eq(a)]
    sort_procv = procv.sort_values(["Data_new"])
    last_game = sort_procv[len(sort_procv)-1:len(sort_procv)]
    last_game = last_game.reset_index(drop=True)
    last_game = last_game.drop(["Confronto","Data_new",'Gls','sofifa_id'],axis=1)
    base_nova_fora = base_nova_fora.append(last_game)

base_nova_casa_op = base_nova_casa[['media_Sh', 'media_SoT', 'media_CrdY', 'media_Touches',
       'media_Tkl', 'media_Int', 'age', 'height_cm', 'weight_kg', 'overall',
       'potential', 'international_reputation', 'weak_foot', 'skill_moves',
       'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']]

base_nova_fora_op = base_nova_fora[['media_Sh', 'media_SoT', 'media_CrdY', 'media_Touches',
       'media_Tkl', 'media_Int', 'age', 'height_cm', 'weight_kg', 'overall',
       'potential', 'international_reputation', 'weak_foot', 'skill_moves',
       'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']]

base_nova_tratada = base_nova_casa_op - base_nova_fora_op
base_nova_tratada = base_nova_tratada.reset_index(drop=True)
base_nova_tratada["Time"] = resultado.Home
base_nova_tratada["Time_Fora"] = resultado.Away
base_nova_tratada["Result"] = ""
base_nova_tratada["N_Gols"] = ""
base_previsao = base_nova_tratada.reset_index(drop=True)
base_previsao = base_previsao[['Time','Time_Fora','media_Sh', 'media_SoT', 'media_CrdY', 'media_Touches', 'media_Tkl',
                               'media_Int', 'age', 'height_cm', 'weight_kg', 'overall', 'potential',
                               'international_reputation', 'weak_foot', 'skill_moves', 'pace','shooting',
                               'passing', 'dribbling', 'defending', 'physic', 'Result', 'N_Gols']]

base_previsao
# teste_bob_2 = pd.concat([teste_bob_2, df4], axis=1, sort=False)

,Time,Time_Fora,media_Sh,media_SoT,media_CrdY,media_Touches,media_Tkl,media_Int,age,height_cm,...,weak_foot,skill_moves,pace,shooting,passing,dribbling,defending,physic,Result,N_Gols
0,Inter,Sassuolo,2.250000,1.125000,-0.041667,-27.291667,-1.833333,0.500000,0.630943,-0.315068,...,0.305197,0.241539,3.619057,5.885375,6.224214,5.337832,4.982877,3.332998,,
1,Atalanta,Lazio,4.311667,1.733333,-0.511667,58.250000,1.086667,-0.151667,-0.839646,1.676768,...,-0.244949,-0.133838,-3.429293,-4.479798,-3.585859,-3.896465,-1.920455,-1.083333,,
2,Roma,Sampdoria,2.255000,1.163333,-0.001667,104.266667,-5.265000,1.645000,0.680527,1.158004,...,0.054747,0.055787,1.287249,4.912682,2.989605,3.388080,4.576923,2.327443,,

In [125]:
#escrevendo em excelfile
writer = pd.ExcelWriter('Base_Previsao_'+link+'.xlsx')
base_previsao.to_excel(writer,"Geral")
writer.save()